In [1]:
import pymysql
import pandas as pd
from sqlalchemy import create_engine

host = 'localhost'
port = '3306'
username = 'root'
password = ''
database = 'classicmodels'

#create connection to database

engine = create_engine('mysql+pymysql://'+username+':'+password+'@'+host+':'+port+'/'+database)
# '''engine = create_engine('mysql+pymysql://root: @localhost:3306/academic')'''

def run(sql):
    df = pd.read_sql_query(sql, engine)
    return df

In [2]:
run("""SELECT
            *
        FROM
            customers
""")

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,France,1370.0,21000.0
1,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,None,Las Vegas,NV,83030,USA,1166.0,71800.0
2,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611.0,117300.0
3,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",None,Nantes,None,44000,France,1370.0,118200.0
4,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,None,Stavern,None,4110,Norway,1504.0,81700.0
5,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,None,San Rafael,CA,97562,USA,1165.0,210500.0
6,125,Havel & Zbyszek Co,Piestrzeniewicz,Zbyszek,(26) 642-7555,ul. Filtrowa 68,None,Warszawa,None,01-012,Poland,NaN,0.0
7,128,"Blauer See Auto, Co.",Keitel,Roland,+49 69 66 90 2555,Lyonerstr. 34,None,Frankfurt,None,60528,Germany,1504.0,59700.0
8,129,Mini Wheels Co.,Murphy,Julie,6505555787,5557 North Pendale Street,None,San Francisco,CA,94217,USA,1165.0,64600.0
9,131,Land of Toys Inc.,Lee,Kwai,2125557818,897 Long Airport Avenue,None,NYC,NY,10022,USA,1323.0,114900.0
10,141,Euro+ Shopping Channel,Freyre,Diego,(91) 555 94 44,"C/ Moralzarzal, 86",None,Madrid,None,28034,Spain,1370.0,227600.0
11,144,"Volvo Model Replicas, Co",Berglund,Christina,0921-12 3555,Berguvsvägen 8,None,Luleå,None,S-958 22,Sweden,1504.0,53100.0
12,145,Danish Wholesale Imports,Petersen,Jytte,31 12 3555,Vinbæltet 34,None,Kobenhavn,None,1734,Denmark,1401.0,83400.0
13,146,"Saveley & Henriot, Co.",Saveley,Mary,78.32.5555,"2, rue du Commerce",None,Lyon,None,69004,France,1337.0,123900.0
14,148,"Dragon Souveniers, Ltd.",Natividad,Eric,+65 221 7555,Bronz Sok.,Bronz Apt. 3/6 Tesvikiye,Singapore,None,079903,Singapore,1621.0,103800.0
15,151,Muscle Machine Inc,Young,Jeff,2125557413,4092 Furth Circle,Suite 400,NYC,NY,10022,USA,1286.0,138500.0
16,157,Diecast Classics Inc.,Leong,Kelvin,2155551555,7586 Pompton St.,None,Allentown,PA,70267,USA,1216.0,100600.0
17,161,Technics Stores Inc.,Hashimoto,Juri,6505556809,9408 Furth Circle,None,Burlingame,CA,94217,USA,1165.0,84600.0
18,166,Handji Gifts& Co,Victorino,Wendy,+65 224 1555,106 Linden Road Sandown,2nd Floor,Singapore,None,069045,Singapore,1612.0,97900.0
19,167,Herkku Gifts,Oeztan,Veysel,+47 2267 3215,Brehmen St. 121,PR 334 Sentrum,Bergen,None,N 5804,Norway,1504.0,96800.0
20,168,American Souvenirs Inc,Franco,Keith,2035557845,149 Spinnaker Dr.,Suite 101,New Haven,CT,97823,USA,1286.0,0.0
21,169,Porto Imports Co.,de Castro,Isabel,(1) 356-5555,Estrada da saúde n. 58,None,Lisboa,None,1756,Portugal,NaN,0.0
22,171,Daedalus Designs Imports,Rancé,Martine,20.16.1555,"184, chaussée de Tournai",None,Lille,None,59000,France,1370.0,82900.0
23,172,"La Corne D'abondance, Co.",Bertrand,Marie,(1) 42.34.2555,"265, boulevard Charonne",None,Paris,None,75012,France,1337.0,84300.0
24,173,Cambridge Collectables Co.,Tseng,Jerry,6175555555,4658 Baden Av.,None,Cambridge,MA,51247,USA,1188.0,43400.0
25,175,Gift Depot Inc.,King,Julie,2035552570,25593 South Bay Ln.,None,Bridgewater,CT,97562,USA,1323.0,84300.0
26,177,Osaka Souveniers Co.,Kentary,Mory,+81 06 6342 5555,1-6-20 Dojima,None,Kita-ku,Osaka,530-0003,Japan,1621.0,81200.0
27,181,Vitachrome Inc.,Frick,Michael,2125551500,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,1286.0,76400.0
28,186,"Toys of Finland, Co.",Karttunen,Matti,90-224 8555,Keskuskatu 45,None,Helsinki,None,21240,Finland,1501.0,96500.0
29,187,"AV Stores, Co.",Ashworth,Rachel,(171) 555-1555,Fauntleroy Circus,None,Manchester,None,EC2 5NT,UK,1501.0,136800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,386,L'ordine Souveniers,Moroni,Maurizio,0522-556555,Strada Provinciale 124,None,Reggio Emilia,None,42100,Italy,1401.0,121400.0
93,398,"Tokyo Collectables, Ltd",Shimamura,Akiko,+81 3 3584 0555,2-2-8 Roppongi,None,Minato-ku,Tokyo,106-0032,Japan,1621.0,94400.0
94,406,Auto Canal+ Petit,Perrier,Dominique,(1) 47.55.6555,"25, rue Lauriston",None,Paris,None,75016,France,1337.0,95000.0
95,409,Stuttgart Collectable Exchange,Müller,Rita,0711-555361,Adenauerallee 900,None,Stuttgart,None,70563,Germany,NaN,0.0
96,412,"Extreme Desk Decorations, Ltd",McRoy,Sarah,04 499 9555,101 Lambton Quay,Level 11,Wellington,None,None,New Zealand,1612.0,86800.0
97,415,"Bavarian Collectables Imports, Co.",Donnermeyer,Michael,+49 89 61 08 9555,Hansastr. 15,None,Munich,None,80686,Germany,1504.0,77000.0
98,424,Classic Legends Inc.,Hernandez,Maria,2125558493,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,1286.0,67500.0
99,443,"Feuer Online Stores, Inc",Feuer,Alexander,0342-555176,Heerstr. 22,None,Leipzig,None,04179,Germany,NaN,0.0
100,447,Gift Ideas Corp.,Lewis,Dan,2035554407,2440 Pompton St.,None,Glendale,CT,97561,USA,1323.0,49700.0
101,448,Scandinavian Gift Ideas,Larsson,Martha,0695-34 6555,Åkergatan 24,None,Bräcke,None,S-844 67,Sweden,1504.0,116400.0
102,450,The Sharp Gifts Warehouse,Frick,Sue,4085553659,3086 Ingle Ln.,None,San Jose,CA,94217,USA,1165.0,77600.0
103,452,Mini Auto Werke,Mendel,Roland,7675-3555,Kirchgasse 6,None,Graz,None,8010,Austria,1401.0,45300.0
104,455,Super Scale Inc.,Murphy,Leslie,2035559545,567 North Pendale Street,None,New Haven,CT,97823,USA,1286.0,95400.0
105,456,Microscale Inc.,Choi,Yu,2125551957,5290 North Pendale Street,Suite 200,NYC,NY,10022,USA,1286.0,39800.0
106,458,"Corrida Auto Replicas, Ltd",Sommer,Martín,(91) 555 22 82,"C/ Araquil, 67",None,Madrid,None,28023,Spain,1702.0,104600.0
107,459,Warburg Exchange,Ottlieb,Sven,0241-039123,Walserweg 21,None,Aachen,None,52066,Germany,NaN,0.0
108,462,FunGiftIdeas.com,Benitez,Violeta,5085552555,1785 First Street,None,New Bedford,MA,50553,USA,1216.0,85800.0
109,465,"Anton Designs, Ltd.",Anton,Carmen,+34 913 728555,"c/ Gobelas, 19-1 Urb. La Florida",None,Madrid,None,28023,Spain,NaN,0.0
110,471,"Australian Collectables, Ltd",Clenahan,Sean,61-9-3844-6555,7 Allen Street,None,Glen Waverly,Victoria,3150,Australia,1611.0,60300.0
111,473,Frau da Collezione,Ricotti,Franco,+39 022515555,20093 Cologno Monzese,Alessandro Volta 16,Milan,None,None,Italy,1401.0,34800.0
112,475,West Coast Collectables Co.,Thompson,Steve,3105553722,3675 Furth Circle,None,Burbank,CA,94019,USA,1166.0,55400.0
113,477,Mit Vergnügen & Co.,Moos,Hanna,0621-08555,Forsterstr. 57,None,Mannheim,None,68306,Germany,NaN,0.0
114,480,"Kremlin Collectables, Co.",Semenov,Alexander,+7 812 293 0521,2 Pobedy Square,None,Saint Petersburg,None,196143,Russia,NaN,0.0
115,481,"Raanan Stores, Inc","Altagar,G M",Raanan,+ 972 9 959 8555,3 Hagalim Blv.,None,Herzlia,None,47625,Israel,NaN,0.0
116,484,"Iberia Gift Imports, Corp.",Roel,José Pedro,(95) 555 82 82,"C/ Romero, 33",None,Sevilla,None,41101,Spain,1702.0,65700.0
117,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,None,Philadelphia,PA,71270,USA,1323.0,72600.0
118,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,None,Brisbane,CA,94217,USA,1165.0,60300.0
119,489,"Double Decker Gift Stores, Ltd",Smith,Thomas,(171) 555-7555,120 Hanover Sq.,None,London,None,WA1 1DP,UK,1501.0,43300.0
120,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,None,Boston,MA,51003,USA,1188.0,85100.0
121,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,New Zealand,1612.0,110000.0

In [11]:
#csv to dataframe to mysql
df_fromcsv = pd.read_csv('personalcustomers.csv')
df_fromcsv.to_sql(name = 'personalcustomers', con = engine, if_exists = 'replace', index = False)
#if_exist = 'fail' | 'replace' | 'append'

In [9]:
#dataframe to csv/excel

df_customers = run("""SELECT
            *
        FROM
            customers
""")

df_customers.to_excel('customers.xlsx', index = False)

In [15]:
#Select all mahasiswa data using run function (pandas)
#data in dataframe type
df_result = run("SELECT * FROM personalcustomers")
print (df_result)

    id   name
0  101   Ryan
1  102  Bruce
2  111  Dylan
3  112   Dale
4  121   Jovi

In [19]:
#insert with autocommit
engine.execute("INSERT INTO personalcustomers VALUES (122, 'Andre')")

In [20]:
#insert with Autocommit
id_pc = '133'
name_pc = 'Cole'
engine.execute("INSERT INTO personalcustomers VALUES("+id_pc+", '"+name_pc+"')")
#jika untuk tabel tertentu 'VALUE' dirubah sesuai kolomnya

In [21]:
df_result = run("SELECT * FROM personalcustomers")
print (df_result)

    id   name
0  101   Ryan
1  102  Bruce
2  111  Dylan
3  112   Dale
4  121   Jovi
5  122  Andre
6  133   Cole
7  122  Andre
8  133   Cole

In [23]:
#update data
engine.execute("UPDATE personalcustomers SET name ='Chris' WHERE id=133 ")

In [24]:
df_result = run("SELECT * FROM personalcustomers")
print (df_result)

    id   name
0  101   Ryan
1  102  Bruce
2  111  Dylan
3  112   Dale
4  121   Jovi
5  122  Andre
6  133  Chris
7  122  Andre
8  133  Chris

In [29]:
engine.execute("UPDATE personalcustomers SET name ='Chris' WHERE id=133 ")

In [31]:
#SubQuery menggunakan operator comparison

run("""SELECT
            customerName
        FROM
            customers
        WHERE
            customerNumber = 
            (SELECT
                customerNumber
            FROM
                payments
            WHERE amount = (SELECT MAX(amount) FROM payments))
""")

             customerName
0  Euro+ Shopping Channel

In [32]:
run("""SELECT
            customerName
        FROM
            customers
        WHERE
            customernumber NOT IN
                (SELECT DISTINCT customerNumber FROM orders)
""")

                      customerName
0               Havel & Zbyszek Co
1           American Souvenirs Inc
2                Porto Imports Co.
3       Asian Shopping Network, Co
4                  Natürlich Autos
5                    ANG Resellers
6         Messner Shopping Network
7                Franken Gifts, Co
8                BG&E Collectables
9                 Schuyler Imports
10                Der Hund Imports
11       Cramer Spezialitäten, Ltd
12           Asian Treasures, Inc.
13            SAR Distributors, Co
14                 Kommission Auto
15          Lisboa Souveniers, Inc
16           Precious Collectables
17  Stuttgart Collectable Exchange
18        Feuer Online Stores, Inc
19                Warburg Exchange
20             Anton Designs, Ltd.
21             Mit Vergnügen & Co.
22       Kremlin Collectables, Co.
23              Raanan Stores, Inc

In [ ]:
run("""SELECT
            MAX(items), MIN(items), FLOOR(AVG(items))
        FROM 
""")