In [1]:
import pymysql
import pandas as pd

host = '127.0.0.1'
port = "3306"
user = 'root'
password = ''
database = 'classicmodels'

conn = pymysql.connect(
    host=host,
    port=int(port),
    user=user,
    passwd=password,
    db=database,
    charset='utf8mb4')

def run(sql):
    df = pd.read_sql_query(sql,conn)
    return df

## One to many relationship
### 1. Report the account representative for each customer

In [4]:
run("""SELECT
    c.customerNumber, c.customerName, c.salesrepemployeenumber,
    e.employeenumber, CONCAT(e.lastname,', ', e.firstname) AS 'employeeName'    
    FROM
    customers c LEFT JOIN employees e ON
    c.salesrepemployeenumber = e.employeenumber
""")

,customerNumber,customerName,salesrepemployeenumber,employeenumber,employeeName
0,103,Atelier graphique,1370.0,1370.0,"Hernandez, Gerard"
1,112,Signal Gift Stores,1166.0,1166.0,"Thompson, Leslie"
2,114,"Australian Collectors, Co.",1611.0,1611.0,"Fixter, Andy"
3,119,La Rochelle Gifts,1370.0,1370.0,"Hernandez, Gerard"
4,121,Baane Mini Imports,1504.0,1504.0,"Jones, Barry"
5,124,Mini Gifts Distributors Ltd.,1165.0,1165.0,"Jennings, Leslie"
6,125,Havel & Zbyszek Co,NaN,NaN,None
7,128,"Blauer See Auto, Co.",1504.0,1504.0,"Jones, Barry"
8,129,Mini Wheels Co.,1165.0,1165.0,"Jennings, Leslie"
9,131,Land of Toys Inc.,1323.0,1323.0,"Vanauf, George"
10,141,Euro+ Shopping Channel,1370.0,1370.0,"Hernandez, Gerard"
11,144,"Volvo Model Replicas, Co",1504.0,1504.0,"Jones, Barry"
12,145,Danish Wholesale Imports,1401.0,1401.0,"Castillo, Pamela"
13,146,"Saveley & Henriot, Co.",1337.0,1337.0,"Bondur, Loui"
14,148,"Dragon Souveniers, Ltd.",1621.0,1621.0,"Nishi, Mami"
15,151,Muscle Machine Inc,1286.0,1286.0,"Tseng, Foon Yue"
16,157,Diecast Classics Inc.,1216.0,1216.0,"Patterson, Steve"
17,161,Technics Stores Inc.,1165.0,1165.0,"Jennings, Leslie"
18,166,Handji Gifts& Co,1612.0,1612.0,"Marsh, Peter"
19,167,Herkku Gifts,1504.0,1504.0,"Jones, Barry"
20,168,American Souvenirs Inc,1286.0,1286.0,"Tseng, Foon Yue"
21,169,Porto Imports Co.,NaN,NaN,None
22,171,Daedalus Designs Imports,1370.0,1370.0,"Hernandez, Gerard"
23,172,"La Corne D'abondance, Co.",1337.0,1337.0,"Bondur, Loui"
24,173,Cambridge Collectables Co.,1188.0,1188.0,"Firrelli, Julie"
25,175,Gift Depot Inc.,1323.0,1323.0,"Vanauf, George"
26,177,Osaka Souveniers Co.,1621.0,1621.0,"Nishi, Mami"
27,181,Vitachrome Inc.,1286.0,1286.0,"Tseng, Foon Yue"
28,186,"Toys of Finland, Co.",1501.0,1501.0,"Bott, Larry"
29,187,"AV Stores, Co.",1501.0,1501.0,"Bott, Larry"
...,...,...,...,...,...
92,386,L'ordine Souveniers,1401.0,1401.0,"Castillo, Pamela"
93,398,"Tokyo Collectables, Ltd",1621.0,1621.0,"Nishi, Mami"
94,406,Auto Canal+ Petit,1337.0,1337.0,"Bondur, Loui"
95,409,Stuttgart Collectable Exchange,NaN,NaN,None
96,412,"Extreme Desk Decorations, Ltd",1612.0,1612.0,"Marsh, Peter"
97,415,"Bavarian Collectables Imports, Co.",1504.0,1504.0,"Jones, Barry"
98,424,Classic Legends Inc.,1286.0,1286.0,"Tseng, Foon Yue"
99,443,"Feuer Online Stores, Inc",NaN,NaN,None
100,447,Gift Ideas Corp.,1323.0,1323.0,"Vanauf, George"
101,448,Scandinavian Gift Ideas,1504.0,1504.0,"Jones, Barry"
102,450,The Sharp Gifts Warehouse,1165.0,1165.0,"Jennings, Leslie"
103,452,Mini Auto Werke,1401.0,1401.0,"Castillo, Pamela"
104,455,Super Scale Inc.,1286.0,1286.0,"Tseng, Foon Yue"
105,456,Microscale Inc.,1286.0,1286.0,"Tseng, Foon Yue"
106,458,"Corrida Auto Replicas, Ltd",1702.0,1702.0,"Gerard, Martin"
107,459,Warburg Exchange,NaN,NaN,None
108,462,FunGiftIdeas.com,1216.0,1216.0,"Patterson, Steve"
109,465,"Anton Designs, Ltd.",NaN,NaN,None
110,471,"Australian Collectables, Ltd",1611.0,1611.0,"Fixter, Andy"
111,473,Frau da Collezione,1401.0,1401.0,"Castillo, Pamela"
112,475,West Coast Collectables Co.,1166.0,1166.0,"Thompson, Leslie"
113,477,Mit Vergnügen & Co.,NaN,NaN,None
114,480,"Kremlin Collectables, Co.",NaN,NaN,None
115,481,"Raanan Stores, Inc",NaN,NaN,None
116,484,"Iberia Gift Imports, Corp.",1702.0,1702.0,"Gerard, Martin"
117,486,Motor Mint Distributors Inc.,1323.0,1323.0,"Vanauf, George"
118,487,Signal Collectibles Ltd.,1165.0,1165.0,"Jennings, Leslie"
119,489,"Double Decker Gift Stores, Ltd",1501.0,1501.0,"Bott, Larry"
120,495,Diecast Collectables,1188.0,1188.0,"Firrelli, Julie"
121,496,Kelly's Gift Shop,1612.0,1612.0,"Marsh, Peter"

In [5]:
run("""SELECT
    c.customerNumber, c.customerName, c.salesrepemployeenumber,
    e.employeenumber, CONCAT(e.lastname,', ', e.firstname) AS 'employeeName'    
    FROM
    customers c LEFT JOIN employees e ON
    c.salesrepemployeenumber = e.employeenumber
    WHERE c.salesrepemployeenumber IS NOT NULL""")

,customerNumber,customerName,salesrepemployeenumber,employeenumber,employeeName
0,103,Atelier graphique,1370,1370,"Hernandez, Gerard"
1,112,Signal Gift Stores,1166,1166,"Thompson, Leslie"
2,114,"Australian Collectors, Co.",1611,1611,"Fixter, Andy"
3,119,La Rochelle Gifts,1370,1370,"Hernandez, Gerard"
4,121,Baane Mini Imports,1504,1504,"Jones, Barry"
5,124,Mini Gifts Distributors Ltd.,1165,1165,"Jennings, Leslie"
6,128,"Blauer See Auto, Co.",1504,1504,"Jones, Barry"
7,129,Mini Wheels Co.,1165,1165,"Jennings, Leslie"
8,131,Land of Toys Inc.,1323,1323,"Vanauf, George"
9,141,Euro+ Shopping Channel,1370,1370,"Hernandez, Gerard"
10,144,"Volvo Model Replicas, Co",1504,1504,"Jones, Barry"
11,145,Danish Wholesale Imports,1401,1401,"Castillo, Pamela"
12,146,"Saveley & Henriot, Co.",1337,1337,"Bondur, Loui"
13,148,"Dragon Souveniers, Ltd.",1621,1621,"Nishi, Mami"
14,151,Muscle Machine Inc,1286,1286,"Tseng, Foon Yue"
15,157,Diecast Classics Inc.,1216,1216,"Patterson, Steve"
16,161,Technics Stores Inc.,1165,1165,"Jennings, Leslie"
17,166,Handji Gifts& Co,1612,1612,"Marsh, Peter"
18,167,Herkku Gifts,1504,1504,"Jones, Barry"
19,168,American Souvenirs Inc,1286,1286,"Tseng, Foon Yue"
20,171,Daedalus Designs Imports,1370,1370,"Hernandez, Gerard"
21,172,"La Corne D'abondance, Co.",1337,1337,"Bondur, Loui"
22,173,Cambridge Collectables Co.,1188,1188,"Firrelli, Julie"
23,175,Gift Depot Inc.,1323,1323,"Vanauf, George"
24,177,Osaka Souveniers Co.,1621,1621,"Nishi, Mami"
25,181,Vitachrome Inc.,1286,1286,"Tseng, Foon Yue"
26,186,"Toys of Finland, Co.",1501,1501,"Bott, Larry"
27,187,"AV Stores, Co.",1501,1501,"Bott, Larry"
28,189,"Clover Collections, Co.",1504,1504,"Jones, Barry"
29,198,Auto-Moto Classics Inc.,1216,1216,"Patterson, Steve"
...,...,...,...,...,...
70,362,Gifts4AllAges.com,1216,1216,"Patterson, Steve"
71,363,Online Diecast Creations Co.,1216,1216,"Patterson, Steve"
72,376,Precious Collectables,1702,1702,"Gerard, Martin"
73,379,Collectables For Less Inc.,1188,1188,"Firrelli, Julie"
74,381,Royale Belge,1401,1401,"Castillo, Pamela"
75,382,Salzburg Collectables,1401,1401,"Castillo, Pamela"
76,385,Cruz & Sons Co.,1621,1621,"Nishi, Mami"
77,386,L'ordine Souveniers,1401,1401,"Castillo, Pamela"
78,398,"Tokyo Collectables, Ltd",1621,1621,"Nishi, Mami"
79,406,Auto Canal+ Petit,1337,1337,"Bondur, Loui"
80,412,"Extreme Desk Decorations, Ltd",1612,1612,"Marsh, Peter"
81,415,"Bavarian Collectables Imports, Co.",1504,1504,"Jones, Barry"
82,424,Classic Legends Inc.,1286,1286,"Tseng, Foon Yue"
83,447,Gift Ideas Corp.,1323,1323,"Vanauf, George"
84,448,Scandinavian Gift Ideas,1504,1504,"Jones, Barry"
85,450,The Sharp Gifts Warehouse,1165,1165,"Jennings, Leslie"
86,452,Mini Auto Werke,1401,1401,"Castillo, Pamela"
87,455,Super Scale Inc.,1286,1286,"Tseng, Foon Yue"
88,456,Microscale Inc.,1286,1286,"Tseng, Foon Yue"
89,458,"Corrida Auto Replicas, Ltd",1702,1702,"Gerard, Martin"
90,462,FunGiftIdeas.com,1216,1216,"Patterson, Steve"
91,471,"Australian Collectables, Ltd",1611,1611,"Fixter, Andy"
92,473,Frau da Collezione,1401,1401,"Castillo, Pamela"
93,475,West Coast Collectables Co.,1166,1166,"Thompson, Leslie"
94,484,"Iberia Gift Imports, Corp.",1702,1702,"Gerard, Martin"
95,486,Motor Mint Distributors Inc.,1323,1323,"Vanauf, George"
96,487,Signal Collectibles Ltd.,1165,1165,"Jennings, Leslie"
97,489,"Double Decker Gift Stores, Ltd",1501,1501,"Bott, Larry"
98,495,Diecast Collectables,1188,1188,"Firrelli, Julie"
99,496,Kelly's Gift Shop,1612,1612,"Marsh, Peter"

### 2. Report total payments for Atelier graphique.

In [11]:
run(""" SELECT
    c.customerName,
    SUM(p.amount) AS 'jumlah'
    FROM
    customers c INNER JOIN payments p ON c.customernumber = p.customernumber
    WHERE c.customerName = 'atelier graphique'
    
""")

        customerName    jumlah
0  Atelier graphique  22314.36

### 3. Report the total payments by date

In [21]:
run(""" SELECT
    m.paymentDate,
    SUM(p.amount) AS 'jumlah'
    FROM
    payments p INNER JOIN payments m ON m.paymentdate = p.paymentdate
    GROUP BY m.paymentDate
""")

    paymentDate     jumlah
0    2003-01-16   10223.83
1    2003-01-28   10549.01
2    2003-01-30    5494.78
3    2003-02-16   50218.95
4    2003-02-20   53959.21
5    2003-02-25   40206.20
6    2003-03-02   52151.81
7    2003-03-09   51001.22
8    2003-03-12   22292.62
9    2003-03-20   25833.14
10   2003-03-27   48425.69
11   2003-04-09   48425.58
12   2003-04-11   11044.30
13   2003-04-16   21665.98
14   2003-04-19    1627.56
15   2003-04-20   33383.14
16   2003-04-22   44380.15
17   2003-05-09    3101.40
18   2003-05-12   35826.33
19   2003-05-20   45864.03
20   2003-05-21   16700.47
21   2003-05-25   50824.66
22   2003-05-31    7565.08
23   2003-06-05   14571.44
24   2003-06-06   32641.98
25   2003-06-13   57131.92
26   2003-06-18   58841.35
27   2003-06-25   17032.29
28   2003-07-05    2880.00
29   2003-07-06    6036.96
..          ...        ...
202  2005-02-02   12692.19
203  2005-02-03   14379.90
204  2005-02-06   39580.60
205  2005-02-09   27083.78
206  2005-02-12   28322.83
207  2005-02-14   33967.73
208  2005-02-15   46770.52
209  2005-02-22   49523.67
210  2005-03-01   21432.31
211  2005-03-02    3452.75
212  2005-03-05  101244.59
213  2005-03-10   23602.90
214  2005-03-15   46781.66
215  2005-03-18  120166.58
216  2005-03-25   65071.26
217  2005-03-27    3516.04
218  2005-04-15   30293.77
219  2005-04-16   83598.04
220  2005-04-18   27966.54
221  2005-04-23   12190.85
222  2005-04-30   29848.52
223  2005-05-03   87929.74
224  2005-05-17   17928.09
225  2005-05-18     615.45
226  2005-05-19  150792.52
227  2005-05-20   29070.38
228  2005-05-23   75020.13
229  2005-05-25   30253.75
230  2005-06-03   12432.32
231  2005-06-09   46656.94

[232 rows x 2 columns]